"""Question bank. Same ids/text as frontend/src/lib/mock.ts. Add subjects here."""

MATH_QUESTIONS = {
  "q1": {"category": "Math", "concept": "Adding fractions", "text": "1/2 + 1/3 = ?", "answers": ["5/6"],
         "wrong": {"2/5": ("Adds tops and bottoms", 0.86)},
         "recovery": {"text": "1/4 + 1/5 = ?", "answers": ["9/20"], "wrong": "2/9"},
         "ladder": ["Walk me through it: what did you do with the two denominators?",
                    "Hint: you can only add pieces of the same size. What common denominator fits 2 and 3?",
                    "Explanation: 1/2 = 3/6 and 1/3 = 2/6, so 3/6 + 2/6 = 5/6. Denominators name the piece size, so they are not added."]},
  "q2": {"category": "Math", "concept": "Comparing fractions", "text": "Which is bigger: 1/3 or 1/5?", "answers": ["1/3"],
         "wrong": {"1/5": ("Bigger denominator means bigger fraction", 0.81)},
         "recovery": {"text": "Which is bigger: 1/4 or 1/8?", "answers": ["1/4"], "wrong": "1/8"},
         "ladder": ["Picture a pizza cut into 3 slices, then 5. Which slice is larger, and why?",
                    "Hint: the more pieces a whole is cut into, the smaller each piece gets.",
                    "Explanation: 1/3 = 5/15 and 1/5 = 3/15, so 1/3 is bigger."]},
  "q3": {"category": "Math", "concept": "Simplifying fractions", "text": "Simplify 6/8", "answers": ["3/4", "0.75"],
         "wrong": {"3/8": ("Divides only the numerator", 0.78)},
         "recovery": {"text": "Simplify 4/10", "answers": ["2/5", "0.4"], "wrong": "2/10"},
         "ladder": ["What can you divide the top by? Did you do the same to the bottom?",
                    "Hint: whatever you divide the numerator by, the denominator gets the same treatment.",
                    "Explanation: divide both 6 and 8 by 2 to get 3/4."]},
  "q4": {"category": "Math", "concept": "Multiplying decimals", "text": "What is 1.2 × 0.5?", "answers": ["0.6", "0.60"],
         "wrong": {"6": ("Misplaces the decimal point", 0.84)},
         "recovery": {"text": "What is 0.8 × 0.5?", "answers": ["0.4", "0.40"], "wrong": "4"},
         "ladder": ["Estimate first: 1.2 is about 1, times 0.5 is about half.",
                    "Hint: multiply 12 × 5, then place the decimal so there are 2 total digits after the decimal point.",
                    "Explanation: 1.2 × 0.5 = 0.6 because 12 × 5 = 60 and 60 becomes 0.60."]},
  "q5": {"category": "Math", "concept": "Percentages", "text": "30% of 80 is what?", "answers": ["24"],
         "wrong": {"8": ("Uses 10% instead of 30%", 0.8)},
         "recovery": {"text": "20% of 50 is what?", "answers": ["10"], "wrong": "5"},
         "ladder": ["Think of 30% as 3 groups of 10%.",
                    "Hint: find 10% first, then multiply by 3.",
                    "Explanation: 10% of 80 is 8, so 30% is 3 × 8 = 24."]},
  "q6": {"category": "Math", "concept": "Solving equations", "text": "Solve x + 7 = 15", "answers": ["8"],
         "wrong": {"22": ("Adds instead of subtracting", 0.81)},
         "recovery": {"text": "Solve x - 4 = 9", "answers": ["13"], "wrong": "5"},
         "ladder": ["What operation undoes adding 7?",
                    "Hint: subtract 7 from both sides.",
                    "Explanation: x + 7 = 15 means x = 15 - 7 = 8."]},
  "q7": {"category": "Math", "concept": "Ratios", "text": "If the ratio of apples to oranges is 2:3 and there are 12 apples, how many oranges?", "answers": ["18"],
         "wrong": {"8": ("Uses the wrong part of the ratio", 0.78)},
         "recovery": {"text": "If the ratio of red to blue marbles is 1:4 and there are 5 red marbles, how many blue marbles?", "answers": ["20"], "wrong": "4"},
         "ladder": ["How much does each ratio unit represent?",
                    "Hint: 2 parts correspond to 12 apples, so each part is 6.",
                    "Explanation: 12 ÷ 2 = 6, so 3 parts = 18 oranges."]},
  "q8": {"category": "Math", "concept": "Area of rectangle", "text": "A rectangle is 6 cm by 4 cm. What is its area?", "answers": ["24cm2", "24 cm2", "24 sq cm", "24"],
         "wrong": {"10": ("Adds instead of multiplies", 0.77)},
         "recovery": {"text": "A rectangle is 3 cm by 5 cm. What is its area?", "answers": ["15cm2", "15 cm2", "15"], "wrong": "8"},
         "ladder": ["Area means how many square units fit inside the rectangle.",
                    "Hint: multiply length by width.",
                    "Explanation: 6 × 4 = 24 square centimeters."]},
}

DSA_QUESTIONS = {
  "d1": {"category": "DSA", "concept": "Binary Search", "text": "In the sorted array [2, 4, 6, 8, 10], which index holds 8?", "answers": ["3"],
         "wrong": {"4": ("Off-by-one index error", 0.8)},
         "recovery": {"text": "In [1, 3, 5, 7, 9], which index holds 5?", "answers": ["2"], "wrong": "3"},
         "ladder": ["Think about zero-based indexing. Which position is the middle value of the array?",
                    "Hint: the array is sorted; compare the target with the middle element, then move left or right.",
                    "Explanation: 8 is the 4th element in a zero-based array, so its index is 3."]},
  "d2": {"category": "DSA", "concept": "Queue", "text": "Which data structure uses FIFO ordering?", "answers": ["queue"],
         "wrong": {"stack": ("Confuses FIFO with LIFO", 0.82)},
         "recovery": {"text": "Which data structure removes the most recently added item first?", "answers": ["stack"], "wrong": "queue"},
         "ladder": ["What happens to the first item that was inserted?",
                    "Hint: FIFO means First In, First Out. Which structure always removes the oldest item first?",
                    "Explanation: a queue processes items in arrival order, whereas a stack works LIFO."]},
  "d3": {"category": "DSA", "concept": "Time Complexity", "text": "What is the time complexity of binary search on n elements?", "answers": ["O(log n)", "O(logn)", "o(log n)", "o(logn)"],
         "wrong": {"O(n)": ("Confuses binary search with a linear scan", 0.79)},
         "recovery": {"text": "What is the time complexity of scanning every element in an array of length n?", "answers": ["O(n)", "o(n)"], "wrong": "O(log n)"},
         "ladder": ["Binary search halves the search space each step. How much does the search space shrink?",
                    "Hint: repeated halving is logarithmic growth, not linear growth.",
                    "Explanation: each comparison cuts the remaining elements in half, so the cost is O(log n)."]},
  "d4": {"category": "DSA", "concept": "Hash map", "text": "What is the average time complexity for a key lookup in a hash map?", "answers": ["O(1)", "o(1)"],
         "wrong": {"O(n)": ("Treats hashing as linear search", 0.8)},
         "recovery": {"text": "What is the worst-case lookup time for a hash map if many keys collide?", "answers": ["O(n)", "o(n)"], "wrong": "O(1)"},
         "ladder": ["What happens after the key is hashed?",
                    "Hint: hashing usually maps directly to an index, so the lookup is near constant time.",
                    "Explanation: average-case lookup is O(1) because the key is converted to an index and accessed directly."]},
  "d5": {"category": "DSA", "concept": "Stack", "text": "Which data structure removes the most recently added item first?", "answers": ["stack"],
         "wrong": {"queue": ("Confuses LIFO with FIFO", 0.82)},
         "recovery": {"text": "Which structure processes items in arrival order?", "answers": ["queue"], "wrong": "stack"},
         "ladder": ["Which item is at the top of the stack?",
                    "Hint: LIFO means Last In, First Out.",
                    "Explanation: stacks remove the newest item first, unlike queues which remove the oldest item first."]},
  "d6": {"category": "DSA", "concept": "Linked list traversal", "text": "What is the runtime to find a target value in a singly linked list of length n?", "answers": ["O(n)", "o(n)"],
         "wrong": {"O(1)": ("Assumes direct indexing like an array", 0.79)},
         "recovery": {"text": "What is the runtime to access the last element of a singly linked list by index?", "answers": ["O(n)", "o(n)"], "wrong": "O(1)"},
         "ladder": ["Can you jump directly to the middle or end of a linked list?",
                    "Hint: you have to walk node by node.",
                    "Explanation: without random access, you must traverse the list in sequence, so it is O(n)."]},
  "d7": {"category": "DSA", "concept": "Depth-first search", "text": "DFS commonly uses which data structure to track the current path?", "answers": ["stack"],
         "wrong": {"queue": ("Uses breadth-first traversal pattern", 0.81)},
         "recovery": {"text": "BFS usually explores nodes in which order?", "answers": ["queue"], "wrong": "stack"},
         "ladder": ["Which structure naturally supports backtracking?",
                    "Hint: DFS goes deep before wide, often using a stack for recursion or explicit tracking.",
                    "Explanation: DFS uses stack-like behavior to revisit previous nodes as it explores deeper branches."]},
  "d8": {"category": "DSA", "concept": "Big O notation", "text": "Which is smaller growth: O(log n) or O(n)?", "answers": ["O(log n)", "o(log n)", "log n"],
         "wrong": {"O(n)": ("Confuses logarithmic growth with linear growth", 0.81)},
         "recovery": {"text": "Which grows faster as n increases: O(1) or O(log n)?", "answers": ["O(log n)", "o(log n)", "log n"], "wrong": "O(1)"},
         "ladder": ["Think about how many times you can halve a number before getting to 1.",
                    "Hint: logarithmic growth is much slower than linear growth.",
                    "Explanation: O(log n) grows much more slowly than O(n); repeated halving is smaller than checking each element."]},
}

QUESTIONS = {**MATH_QUESTIONS, **DSA_QUESTIONS}
QUESTION_BANKS = {"Math": list(MATH_QUESTIONS.values()), "DSA": list(DSA_QUESTIONS.values())}
CONCEPTS = [q["concept"] for q in QUESTIONS.values()]
INITIAL_MASTERY = dict(zip(CONCEPTS, [0.35, 0.4, 0.5, 0.45, 0.55, 0.5, 0.6, 0.52, 0.48, 0.58, 0.46, 0.54, 0.62, 0.5, 0.57, 0.49]))
